manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5          # 0.005 → 0.5 로 100배 늘려줍니다.
  kinematics_solver_attempts: 10
  solve_type: Distance
  position_only_ik: false

