/**:
  ros__parameters:
    filter1:
      name: polygon_filter
      type: laser_filters/LaserScanPolygonFilter
      params:
        polygon_frame: base_link
        polygon: '[[0.15, 0.2], [0.15, -0.2], [-0.45, -0.2], [-0.45, 0.2]]'
        invert: false